[package]
name = "lxmf-grpc-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
tonic-prost-build = "0.14"
protoc-bin-vendored = "3"

[lints]
workspace = true
