const IDENTITY_SDK_OPERATION_SPECS: &[SdkOperationSpec] = &[
    SdkOperationSpec {
        id: "app.identity.list",
        group: "identity",
        kind: "query",
        transport_variant: "rpc",
        description: "List identities visible to the runtime.",
        aliases: &["sdk_identity_list_v2"],
        required_capabilities: &["sdk.capability.identity_multi"],
        rpc_method: "sdk_identity_list_v2",
    },
    SdkOperationSpec {
        id: "app.identity.create",
        group: "identity",
        kind: "command",
        transport_variant: "rpc",
        description: "Create a persistent Reticulum service identity for this session.",
        aliases: &["sdk_identity_create_v2"],
        required_capabilities: &[
            "sdk.capability.identity_multi",
            "sdk.capability.identity_import_export",
        ],
        rpc_method: "sdk_identity_create_v2",
    },
    SdkOperationSpec {
        id: "app.identity.announce",
        group: "identity",
        kind: "command",
        transport_variant: "rpc",
        description: "Trigger an announce for the active identity.",
        aliases: &["sdk_identity_announce_now_v2"],
        required_capabilities: &["sdk.capability.identity_discovery"],
        rpc_method: "sdk_identity_announce_now_v2",
    },
    SdkOperationSpec {
        id: "app.identity.presence.list",
        group: "identity",
        kind: "query",
        transport_variant: "rpc",
        description: "List recently seen peers and announce-derived presence state.",
        aliases: &["sdk_identity_presence_list_v2"],
        required_capabilities: &["sdk.capability.identity_discovery"],
        rpc_method: "sdk_identity_presence_list_v2",
    },
];
