const PROPAGATION_SDK_OPERATION_SPECS: &[SdkOperationSpec] = &[
    SdkOperationSpec {
        id: "app.propagation.peer_sync",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Run a propagation peer sync and return offer, transfer, retry, and queue state.",
        aliases: &["peer_sync"],
        required_capabilities: &[],
        rpc_method: "peer_sync",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_status",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Query remote propagation router status.",
        aliases: &["propagation_remote_status"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_status",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_fetch",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Fetch propagation payloads from a remote router and preserve lifecycle state.",
        aliases: &["propagation_remote_fetch"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_fetch",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_download",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Download propagation payloads from a remote router and preserve lifecycle state.",
        aliases: &["propagation_remote_download"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_download",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_sync",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Run a remote propagation sync for one peer and preserve peer queue state.",
        aliases: &["propagation_remote_sync"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_sync",
    },
    SdkOperationSpec {
        id: "app.propagation.remote_unpeer",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Unpeer through a remote propagation router and report local queue cleanup.",
        aliases: &["propagation_remote_unpeer"],
        required_capabilities: &[],
        rpc_method: "propagation_remote_unpeer",
    },
    SdkOperationSpec {
        id: "app.propagation.acknowledge_sync_completion",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Acknowledge a propagation sync completion or failure and expose the resulting recovery state.",
        aliases: &["propagation_acknowledge_sync_completion"],
        required_capabilities: &[],
        rpc_method: "propagation_acknowledge_sync_completion",
    },
    SdkOperationSpec {
        id: "app.propagation.node.get",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "Return the selected outbound propagation router node.",
        aliases: &["get_outbound_propagation_node"],
        required_capabilities: &[],
        rpc_method: "get_outbound_propagation_node",
    },
    SdkOperationSpec {
        id: "app.propagation.node.set",
        group: "propagation",
        kind: "command",
        transport_variant: "legacy_rpc",
        description: "Select or clear the outbound propagation router node.",
        aliases: &["set_outbound_propagation_node"],
        required_capabilities: &[],
        rpc_method: "set_outbound_propagation_node",
    },
    SdkOperationSpec {
        id: "app.propagation.node.list",
        group: "propagation",
        kind: "query",
        transport_variant: "legacy_rpc",
        description: "List known outbound propagation router nodes and selection state.",
        aliases: &["list_propagation_nodes"],
        required_capabilities: &[],
        rpc_method: "list_propagation_nodes",
    },
];
