use super::*;

#[test]
fn sdk_schema_valid_fixtures_pass_contract_checks() {
    let schemas = load_schemas();
    assert_schema_valid(
        &schemas.event,
        "docs/fixtures/sdk-v2/event.runtime_state.valid.json",
        &fixture("docs/fixtures/sdk-v2/event.runtime_state.valid.json"),
    );
    assert_schema_valid(
        &schemas.event,
        "docs/fixtures/sdk-v2/event.stream_gap.valid.json",
        &fixture("docs/fixtures/sdk-v2/event.stream_gap.valid.json"),
    );
    assert_schema_valid(
        &schemas.config,
        "docs/fixtures/sdk-v2/config.desktop_local.valid.json",
        &fixture("docs/fixtures/sdk-v2/config.desktop_local.valid.json"),
    );
    assert_schema_valid(
        &schemas.config,
        "docs/fixtures/sdk-v2/config.remote_token.valid.json",
        &fixture("docs/fixtures/sdk-v2/config.remote_token.valid.json"),
    );
    assert_schema_valid(
        &schemas.config,
        "docs/fixtures/sdk-v2/config.store_forward.valid.json",
        &fixture("docs/fixtures/sdk-v2/config.store_forward.valid.json"),
    );
    assert_schema_valid(
        &schemas.config,
        "docs/fixtures/sdk-v2/config.event_sink.valid.json",
        &fixture("docs/fixtures/sdk-v2/config.event_sink.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.start.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.start.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.send_group.empty_destination.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.send_group.empty_destination.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.send_group.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.send_group.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_get.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_get.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_create.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_create.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_list.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_list.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_subscribe.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_subscribe.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_unsubscribe.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_unsubscribe.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_publish.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_publish.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.telemetry_query.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.telemetry_query.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.telemetry_subscribe.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.telemetry_subscribe.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_store.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_store.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_upload_start.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_upload_start.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_upload_chunk.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_upload_chunk.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_upload_commit.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_upload_commit.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_get.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_get.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_list.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_list.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_delete.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_delete.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_download.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_download.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_download_chunk.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_download_chunk.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_associate_topic.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_associate_topic.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_create.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_create.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_list.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_list.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_update_position.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_update_position.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_delete.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_delete.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_activate.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_activate.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_list.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_list.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_announce_now.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_announce_now.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_presence_list.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_presence_list.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_contact_update.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_contact_update.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_contact_list.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_contact_list.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_bootstrap.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_bootstrap.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_import.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_import.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_export.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_export.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_resolve.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_resolve.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.paper_encode.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.paper_encode.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.paper_decode.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.paper_decode.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.command_invoke.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.command_invoke.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.command_reply.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.command_reply.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.voice_session_open.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.voice_session_open.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.voice_session_update.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.voice_session_update.valid.json"),
    );
    assert_schema_valid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.voice_session_close.valid.json",
        &fixture("docs/fixtures/sdk-v2/command.voice_session_close.valid.json"),
    );
    assert_schema_valid(
        &schemas.error,
        "docs/fixtures/sdk-v2/error.validation.valid.json",
        &fixture("docs/fixtures/sdk-v2/error.validation.valid.json"),
    );
    assert_schema_valid(
        &schemas.topic,
        "docs/fixtures/sdk-v2/topic.record.valid.json",
        &fixture("docs/fixtures/sdk-v2/topic.record.valid.json"),
    );
    assert_schema_valid(
        &schemas.telemetry,
        "docs/fixtures/sdk-v2/telemetry.point.valid.json",
        &fixture("docs/fixtures/sdk-v2/telemetry.point.valid.json"),
    );
    assert_schema_valid(
        &schemas.attachment,
        "docs/fixtures/sdk-v2/attachment.meta.valid.json",
        &fixture("docs/fixtures/sdk-v2/attachment.meta.valid.json"),
    );
    assert_schema_valid(
        &schemas.marker,
        "docs/fixtures/sdk-v2/marker.record.valid.json",
        &fixture("docs/fixtures/sdk-v2/marker.record.valid.json"),
    );
    assert_schema_valid(
        &schemas.identity,
        "docs/fixtures/sdk-v2/identity.bundle.valid.json",
        &fixture("docs/fixtures/sdk-v2/identity.bundle.valid.json"),
    );
    assert_schema_valid(
        &schemas.identity,
        "docs/fixtures/sdk-v2/identity.contact_record.valid.json",
        &fixture("docs/fixtures/sdk-v2/identity.contact_record.valid.json"),
    );
    assert_schema_valid(
        &schemas.identity,
        "docs/fixtures/sdk-v2/identity.presence_list.valid.json",
        &fixture("docs/fixtures/sdk-v2/identity.presence_list.valid.json"),
    );
    assert_schema_valid(
        &schemas.paper,
        "docs/fixtures/sdk-v2/paper.envelope.valid.json",
        &fixture("docs/fixtures/sdk-v2/paper.envelope.valid.json"),
    );
    assert_schema_valid(
        &schemas.command_plugin,
        "docs/fixtures/sdk-v2/command-plugin.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/command-plugin.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.voice_signaling,
        "docs/fixtures/sdk-v2/voice-signaling.update.valid.json",
        &fixture("docs/fixtures/sdk-v2/voice-signaling.update.valid.json"),
    );
}
