#[test]
fn sdk_schema_invalid_fixtures_are_rejected() {
    let schemas = load_schemas();
    assert_schema_invalid(
        &schemas.event,
        "docs/fixtures/sdk-v2/event.extension_reserved.invalid.json",
        &fixture("docs/fixtures/sdk-v2/event.extension_reserved.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.config,
        "docs/fixtures/sdk-v2/config.remote_local_trusted.invalid.json",
        &fixture("docs/fixtures/sdk-v2/config.remote_local_trusted.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.config,
        "docs/fixtures/sdk-v2/config.store_forward.invalid.json",
        &fixture("docs/fixtures/sdk-v2/config.store_forward.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.config,
        "docs/fixtures/sdk-v2/config.event_sink.invalid.json",
        &fixture("docs/fixtures/sdk-v2/config.event_sink.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.send_unknown_field.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.send_unknown_field.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.send_group.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.send_group.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_get.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_get.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_create.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_create.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_list.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_list.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_subscribe.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_subscribe.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_unsubscribe.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_unsubscribe.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.topic_publish.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.topic_publish.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.telemetry_query.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.telemetry_query.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.telemetry_subscribe.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.telemetry_subscribe.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_store.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_store.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_upload_start.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_upload_start.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_upload_chunk.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_upload_chunk.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_upload_commit.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_upload_commit.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_get.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_get.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_list.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_list.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_delete.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_delete.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_download.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_download.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_download_chunk.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_download_chunk.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.attachment_associate_topic.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.attachment_associate_topic.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_create.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_create.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_list.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_list.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_update_position.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_update_position.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.marker_delete.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.marker_delete.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.voice_session_open.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.voice_session_open.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_list.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_list.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_announce_now.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_announce_now.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_presence_list.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_presence_list.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_contact_update.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_contact_update.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_contact_list.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_contact_list.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_bootstrap.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_bootstrap.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_activate.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_activate.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_import.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_import.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_export.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_export.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.identity_resolve.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.identity_resolve.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.paper_encode.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.paper_encode.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.paper_decode.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.paper_decode.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.command_reply.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.command_reply.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.command_invoke.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.command_invoke.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.voice_session_update.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.voice_session_update.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.command,
        "docs/fixtures/sdk-v2/command.voice_session_close.invalid.json",
        &fixture("docs/fixtures/sdk-v2/command.voice_session_close.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.error,
        "docs/fixtures/sdk-v2/error.invalid_machine_code.invalid.json",
        &fixture("docs/fixtures/sdk-v2/error.invalid_machine_code.invalid.json"),
    );
}
