name: lxmf_rpc_chat_app
description: "Flutter chat smoke app for the LXMF RPC app surface."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  lxmf_sdk_app:
    path: ../lxmf_sdk_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
