#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ERROR_CODES_JSON = ROOT / "docs/contracts/node-error-codes-v1.json"
RUST_OUT = ROOT / "crates/libs/rns-embedded-ffi/src/generated/node_error_codes.rs"
C_OUT = ROOT / "crates/libs/rns-embedded-ffi/include/generated/rns_embedded_v1_node_error_codes.inc"
DOC_OUT = ROOT / "docs/contracts/node-error-codes-v1.md"


def load_error_codes() -> dict:
    return json.loads(ERROR_CODES_JSON.read_text())


def rust_enum(data: dict) -> str:
    lines = [
        "// @generated by scripts/generate_embedded_node_contracts.py",
        "// Source: docs/contracts/node-error-codes-v1.json",
        "",
        "#[repr(C)]",
        "#[derive(Debug, Clone, Copy, Eq, PartialEq)]",
        "pub enum RnsEmbeddedV1NodeErrorCode {",
    ]
    for code in data["codes"]:
        lines.append(f"    /// {code['description']}")
        lines.append(f"    {code['rust_variant']} = {code['value']},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def c_enum_fragment(data: dict) -> str:
    lines = [
        "/* @generated by scripts/generate_embedded_node_contracts.py */",
        "/* Source: docs/contracts/node-error-codes-v1.json */",
    ]
    for code in data["codes"]:
        lines.append(f"  /* {code['description']} */")
        lines.append(f"  {code['c_name']} = {code['value']},")
    lines.append("")
    return "\n".join(lines)


def markdown_table(data: dict) -> str:
    lines = [
        "# Embedded Node Error Codes v1",
        "",
        "Generated from [node-error-codes-v1.json](./node-error-codes-v1.json).",
        "",
        f"Schema version: `{data['schema_version']}`",
        "",
        "| Value | Rust Variant | C Constant | Default FFI Status | Description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for code in data["codes"]:
        lines.append(
            f"| `{code['value']}` | `{code['rust_variant']}` | `{code['c_name']}` | `{code['status']}` | {code['description']} |"
        )
    lines.extend(
        [
            "",
            "Notes:",
            "",
            "- `SUBSCRIPTION_CLOSED`, `NODE_RESTARTED`, and `EVENT_GAP` are sideband semantic codes surfaced alongside successful poll results.",
            "- Wrappers must tolerate new codes added in future schema versions and treat unknown numeric values as opaque but non-fatal contract growth.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    data = load_error_codes()
    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    C_OUT.parent.mkdir(parents=True, exist_ok=True)
    DOC_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.write_text(rust_enum(data))
    C_OUT.write_text(c_enum_fragment(data))
    DOC_OUT.write_text(markdown_table(data))


if __name__ == "__main__":
    main()
