#[derive(Debug, Clone, Default)]
struct RpcMetrics {
    http_requests_total: u64,
    http_request_errors_total: u64,
    rpc_requests_total: u64,
    rpc_errors_total: u64,
    sdk_send_total: u64,
    sdk_send_success_total: u64,
    sdk_send_error_total: u64,
    sdk_poll_total: u64,
    sdk_poll_events_total: u64,
    sdk_poll_batches_with_gap_total: u64,
    sdk_cancel_total: u64,
    sdk_cancel_accepted_total: u64,
    sdk_cancel_too_late_total: u64,
    sdk_cancel_not_found_total: u64,
    sdk_cancel_already_terminal_total: u64,
    sdk_event_drops_total: u64,
    sdk_event_sink_publish_total: u64,
    sdk_event_sink_error_total: u64,
    sdk_event_sink_skipped_total: u64,
    sdk_auth_failures_total: u64,
    ble_connect_failures_total: u64,
    ble_chunk_retries_total: u64,
    ble_nacks_total: u64,
    ble_tx_queue_timeout_total: u64,
    attachment_upload_offset_reject_total: u64,
    attachment_upload_checksum_mismatch_total: u64,
    capture_success_total: u64,
    capture_failure_total: u64,
    http_requests_by_route: BTreeMap<String, u64>,
    rpc_requests_by_method: BTreeMap<String, u64>,
    rpc_errors_by_method: BTreeMap<String, u64>,
    sdk_event_sink_publish_by_kind: BTreeMap<String, u64>,
    sdk_event_sink_errors_by_kind: BTreeMap<String, u64>,
    ble_connect_failures_by_iface: BTreeMap<String, u64>,
    ble_chunk_retries_by_iface_reason: BTreeMap<String, u64>,
    ble_nacks_by_iface: BTreeMap<String, u64>,
    ble_tx_queue_timeout_by_iface: BTreeMap<String, u64>,
    attachment_upload_offset_reject_by_code: BTreeMap<String, u64>,
    capture_success_by_camera_id: BTreeMap<String, u64>,
    capture_failure_by_camera_reason: BTreeMap<String, u64>,
    sdk_send_latency_ms: RpcLatencyHistogram,
    sdk_poll_latency_ms: RpcLatencyHistogram,
    sdk_auth_latency_ms: RpcLatencyHistogram,
    sdk_send_store_write_ns_total: u64,
    sdk_send_store_write_ops_total: u64,
    sdk_send_delivery_schedule_ns_total: u64,
    sdk_send_delivery_schedule_ops_total: u64,
    sdk_send_event_publish_ns_total: u64,
    sdk_send_event_publish_ops_total: u64,
    daemon_status_lock_wait_ns_total: u64,
    daemon_status_snapshot_wait_ns_total: u64,
    daemon_status_message_count_wait_ns_total: u64,
    daemon_status_calls_total: u64,
    sdk_poll_event_log_lock_wait_ns_total: u64,
    sdk_poll_event_log_lock_ops_total: u64,
}

enum EventSinkCommand {
    Publish {
        sink: Arc<dyn EventSinkBridge>,
        sink_kind: String,
        envelope: RpcEventSinkEnvelope,
    },
    #[cfg(test)]
    Flush {
        reply: mpsc::Sender<()>,
    },
}

struct OutboundDeliveryCommand {
    record: MessageRecord,
    options: OutboundDeliveryOptions,
}
