[package]
name = "rns-embedded-mininode"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hex.workspace = true
lxmf-core = { path = "../lxmf-core", version = "0.1.0", default-features = false, features = ["alloc"] }
rand_core.workspace = true
rmp-serde.workspace = true
rmpv.workspace = true
rns-core = { path = "../rns-core", version = "0.1.0", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = ["lxmf-core/std", "rns-core/std"]

[lints]
workspace = true
